#include "plansyncmanager.h"
#include "sqlplandatabase.h"
#include "plan.h"

#include <QDebug>

#if defined(EC_GRPC_ENABLED)
// ── Desktop + Qt gRPC addon ──────────────────────────────────────────────────
#  include <QGrpcHttp2Channel>
#  include <QGrpcChannelOptions>
// Generated by qt_add_protobuf / qt_add_grpc (only when EC_GRPC_ENABLED):
#  include "calendar.qpb.h"
#  include "calendarservice_client.grpc.qpb.h"

#elif defined(Q_OS_WASM)
// ── WASM: REST/JSON via QNetworkAccessManager ────────────────────────────────
#  include <QNetworkAccessManager>
#  include <QNetworkReply>
#  include <QNetworkRequest>
#  include <QJsonDocument>
#  include <QJsonObject>
#  include <QJsonArray>
#endif

// ── Construction ─────────────────────────────────────────────────────────────

PlanSyncManager::PlanSyncManager(SqlPlanDatabase *db, const QUrl &serverUrl, QObject *parent)
    : QObject(parent)
    , m_db(db)
    , m_serverUrl(serverUrl)
{
#if defined(EC_GRPC_ENABLED)
    m_grpcClient = new calendar::CalendarServiceClient(this);
    m_grpcClient->attachChannel(std::make_shared<QGrpcHttp2Channel>(
        m_serverUrl, QGrpcChannelOptions{}));
#elif defined(Q_OS_WASM)
    m_nam = new QNetworkAccessManager(this);
#else
    qDebug() << "[PlanSyncManager] No transport available (Qt gRPC not installed). "
                "Sync disabled — app works locally only.";
#endif
}

PlanSyncManager::~PlanSyncManager() = default;

// ── Public API ────────────────────────────────────────────────────────────────

void PlanSyncManager::start()
{
    connect(m_db, &SqlPlanDatabase::planAdded,   this, &PlanSyncManager::pushAddedPlan);
    connect(m_db, &SqlPlanDatabase::planUpdated, this, &PlanSyncManager::pushUpdatedPlan);
    connect(m_db, &SqlPlanDatabase::planDeleted, this, &PlanSyncManager::pushDeletedPlan);

    syncReferenceData();
}

// ── Reference data sync ───────────────────────────────────────────────────────

void PlanSyncManager::syncReferenceData()
{
#if defined(EC_GRPC_ENABLED)
    // Units
    auto *unitsReply = m_grpcClient->GetUnits(calendar::Empty{});
    connect(unitsReply, &QGrpcCallReply::finished, this, [unitsReply, this]() {
        if (unitsReply->status().isOk()) {
            const auto resp = unitsReply->read<calendar::GetUnitsResponse>();
            QVariantList units;
            for (const auto &u : resp.units()) {
                QVariantMap m;
                m[QStringLiteral("id")]   = u.id();
                m[QStringLiteral("name")] = u.name();
                units << m;
            }
            m_db->setUnits(units);
            qDebug() << "[PlanSyncManager] Loaded" << units.size() << "units from server";
        } else {
            qWarning() << "[PlanSyncManager] GetUnits failed:" << unitsReply->status().message();
        }
        unitsReply->deleteLater();
    });

    // Routes
    auto *routesReply = m_grpcClient->GetRoutes(calendar::Empty{});
    connect(routesReply, &QGrpcCallReply::finished, this, [routesReply, this]() {
        if (routesReply->status().isOk()) {
            const auto resp = routesReply->read<calendar::GetRoutesResponse>();
            QVariantList routes;
            for (const auto &r : resp.routes()) {
                QVariantMap m;
                m[QStringLiteral("id")]   = r.id();
                m[QStringLiteral("name")] = r.name();
                routes << m;
            }
            m_db->setRoutes(routes);
            qDebug() << "[PlanSyncManager] Loaded" << routes.size() << "routes from server";
        } else {
            qWarning() << "[PlanSyncManager] GetRoutes failed:" << routesReply->status().message();
        }
        routesReply->deleteLater();
    });

#elif defined(Q_OS_WASM)
    // Units
    QNetworkRequest unitsReq(QUrl(m_serverUrl.toString() + QStringLiteral("/api/units")));
    auto *unitsReply = m_nam->get(unitsReq);
    connect(unitsReply, &QNetworkReply::finished, this, [unitsReply, this]() {
        if (unitsReply->error() == QNetworkReply::NoError) {
            const QJsonArray arr = QJsonDocument::fromJson(unitsReply->readAll())
                                       .object()[QStringLiteral("units")].toArray();
            QVariantList units;
            for (const QJsonValue &v : arr) {
                QVariantMap m;
                m[QStringLiteral("id")]   = v[QStringLiteral("id")].toInt();
                m[QStringLiteral("name")] = v[QStringLiteral("name")].toString();
                units << m;
            }
            m_db->setUnits(units);
            qDebug() << "[PlanSyncManager] Loaded" << units.size() << "units from server";
        } else {
            qWarning() << "[PlanSyncManager] GET /api/units failed:" << unitsReply->errorString();
        }
        unitsReply->deleteLater();
    });

    // Routes
    QNetworkRequest routesReq(QUrl(m_serverUrl.toString() + QStringLiteral("/api/routes")));
    auto *routesReply = m_nam->get(routesReq);
    connect(routesReply, &QNetworkReply::finished, this, [routesReply, this]() {
        if (routesReply->error() == QNetworkReply::NoError) {
            const QJsonArray arr = QJsonDocument::fromJson(routesReply->readAll())
                                       .object()[QStringLiteral("routes")].toArray();
            QVariantList routes;
            for (const QJsonValue &v : arr) {
                QVariantMap m;
                m[QStringLiteral("id")]   = v[QStringLiteral("id")].toInt();
                m[QStringLiteral("name")] = v[QStringLiteral("name")].toString();
                routes << m;
            }
            m_db->setRoutes(routes);
            qDebug() << "[PlanSyncManager] Loaded" << routes.size() << "routes from server";
        } else {
            qWarning() << "[PlanSyncManager] GET /api/routes failed:" << routesReply->errorString();
        }
        routesReply->deleteLater();
    });

#else
    // No transport — sync disabled, local seed data remains in effect.
#endif
}

// ── Plan push helpers ─────────────────────────────────────────────────────────

void PlanSyncManager::pushAddedPlan(int id)
{
#if defined(EC_GRPC_ENABLED)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    calendar::PlanData data;
    data.setName(plan.name);
    data.setStartDate(plan.startDate.date().toString(Qt::ISODate));
    data.setStartTimeSecs(plan.startDate.time().msecsSinceStartOfDay() / 1000);
    data.setEndDate(plan.endDate.date().toString(Qt::ISODate));
    data.setEndTimeSecs(plan.endDate.time().msecsSinceStartOfDay() / 1000);
    data.setUnitId(plan.unitId);
    QList<int> rids;
    for (int rid : plan.routeIds) rids << rid;
    data.setRouteIds(rids);

    calendar::AddPlanRequest req;
    req.setData(data);

    auto *reply = m_grpcClient->AddPlan(req);
    connect(reply, &QGrpcCallReply::finished, this, [reply, id]() {
        if (!reply->status().isOk())
            qWarning() << "[PlanSyncManager] AddPlan" << id << "failed:" << reply->status().message();
        reply->deleteLater();
    });

#elif defined(Q_OS_WASM)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    QJsonObject body;
    body[QStringLiteral("name")]          = plan.name;
    body[QStringLiteral("startDate")]     = plan.startDate.date().toString(Qt::ISODate);
    body[QStringLiteral("startTimeSecs")] = plan.startDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("endDate")]       = plan.endDate.date().toString(Qt::ISODate);
    body[QStringLiteral("endTimeSecs")]   = plan.endDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("unitId")]        = plan.unitId;
    QJsonArray rids;
    for (int rid : plan.routeIds) rids << rid;
    body[QStringLiteral("routeIds")] = rids;

    QNetworkRequest req(QUrl(m_serverUrl.toString() + QStringLiteral("/api/plans")));
    req.setHeader(QNetworkRequest::ContentTypeHeader, QStringLiteral("application/json"));
    auto *reply = m_nam->post(req, QJsonDocument(body).toJson(QJsonDocument::Compact));
    connect(reply, &QNetworkReply::finished, this, [reply, id]() {
        if (reply->error() != QNetworkReply::NoError)
            qWarning() << "[PlanSyncManager] POST /api/plans (id" << id << "):" << reply->errorString();
        reply->deleteLater();
    });
#else
    Q_UNUSED(id)
#endif
}

void PlanSyncManager::pushUpdatedPlan(int id)
{
#if defined(EC_GRPC_ENABLED)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    calendar::PlanData data;
    data.setName(plan.name);
    data.setStartDate(plan.startDate.date().toString(Qt::ISODate));
    data.setStartTimeSecs(plan.startDate.time().msecsSinceStartOfDay() / 1000);
    data.setEndDate(plan.endDate.date().toString(Qt::ISODate));
    data.setEndTimeSecs(plan.endDate.time().msecsSinceStartOfDay() / 1000);
    data.setUnitId(plan.unitId);
    QList<int> rids;
    for (int rid : plan.routeIds) rids << rid;
    data.setRouteIds(rids);

    calendar::UpdatePlanRequest req;
    req.setId(id);
    req.setData(data);

    auto *reply = m_grpcClient->UpdatePlan(req);
    connect(reply, &QGrpcCallReply::finished, this, [reply, id]() {
        if (!reply->status().isOk())
            qWarning() << "[PlanSyncManager] UpdatePlan" << id << "failed:" << reply->status().message();
        reply->deleteLater();
    });

#elif defined(Q_OS_WASM)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    QJsonObject body;
    body[QStringLiteral("name")]          = plan.name;
    body[QStringLiteral("startDate")]     = plan.startDate.date().toString(Qt::ISODate);
    body[QStringLiteral("startTimeSecs")] = plan.startDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("endDate")]       = plan.endDate.date().toString(Qt::ISODate);
    body[QStringLiteral("endTimeSecs")]   = plan.endDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("unitId")]        = plan.unitId;
    QJsonArray rids;
    for (int rid : plan.routeIds) rids << rid;
    body[QStringLiteral("routeIds")] = rids;

    QNetworkRequest req(QUrl(m_serverUrl.toString()
                             + QStringLiteral("/api/plans/") + QString::number(id)));
    req.setHeader(QNetworkRequest::ContentTypeHeader, QStringLiteral("application/json"));
    auto *reply = m_nam->put(req, QJsonDocument(body).toJson(QJsonDocument::Compact));
    connect(reply, &QNetworkReply::finished, this, [reply, id]() {
        if (reply->error() != QNetworkReply::NoError)
            qWarning() << "[PlanSyncManager] PUT /api/plans/" << id << ":" << reply->errorString();
        reply->deleteLater();
    });
#else
    Q_UNUSED(id)
#endif
}

void PlanSyncManager::pushDeletedPlan(int id)
{
#if defined(EC_GRPC_ENABLED)
    calendar::DeletePlanRequest req;
    req.setId(id);

    auto *reply = m_grpcClient->DeletePlan(req);
    connect(reply, &QGrpcCallReply::finished, this, [reply, id]() {
        if (!reply->status().isOk())
            qWarning() << "[PlanSyncManager] DeletePlan" << id << "failed:" << reply->status().message();
        reply->deleteLater();
    });

#elif defined(Q_OS_WASM)
    QNetworkRequest req(QUrl(m_serverUrl.toString()
                             + QStringLiteral("/api/plans/") + QString::number(id)));
    auto *reply = m_nam->deleteResource(req);
    connect(reply, &QNetworkReply::finished, this, [reply, id]() {
        if (reply->error() != QNetworkReply::NoError)
            qWarning() << "[PlanSyncManager] DELETE /api/plans/" << id << ":" << reply->errorString();
        reply->deleteLater();
    });
#else
    Q_UNUSED(id)
#endif
}
