#include "plansyncmanager.h"
#include "sqlplandatabase.h"
#include "plan.h"

#include <QDebug>

#if defined(EC_GRPC_ENABLED)
// ── Desktop: Qt gRPC ─────────────────────────────────────────────────────────
// Generated by qt_add_protobuf / qt_add_grpc into proto_gen/:
#  include "calendar.qpb.h"
#  include "calendar_client.grpc.qpb.h"
#  include <QGrpcHttp2Channel>
#  include <QGrpcChannelOptions>

#elif defined(Q_OS_WASM)
// ── WASM: REST/JSON via QNetworkAccessManager ────────────────────────────────
#  include <QNetworkAccessManager>
#  include <QNetworkReply>
#  include <QNetworkRequest>
#  include <QJsonDocument>
#  include <QJsonObject>
#  include <QJsonArray>
#endif

// ── Construction ─────────────────────────────────────────────────────────────

PlanSyncManager::PlanSyncManager(SqlPlanDatabase *db, const QUrl &serverUrl, QObject *parent)
    : QObject(parent)
    , m_db(db)
    , m_serverUrl(serverUrl)
{
#if defined(EC_GRPC_ENABLED)
    m_grpcClient = new calendar::CalendarService::Client(this);
    m_grpcClient->attachChannel(std::make_shared<QGrpcHttp2Channel>(
        m_serverUrl, QGrpcChannelOptions{}));
#elif defined(Q_OS_WASM)
    m_nam = new QNetworkAccessManager(this);
#else
    qDebug() << "[PlanSyncManager] No transport — sync disabled (install protoc to enable gRPC).";
#endif
}

PlanSyncManager::~PlanSyncManager() = default;

// ── Public API ────────────────────────────────────────────────────────────────

void PlanSyncManager::start()
{
    connect(m_db, &SqlPlanDatabase::planAdded,   this, &PlanSyncManager::pushAddedPlan);
    connect(m_db, &SqlPlanDatabase::planUpdated, this, &PlanSyncManager::pushUpdatedPlan);
    connect(m_db, &SqlPlanDatabase::planDeleted, this, &PlanSyncManager::pushDeletedPlan);

    syncReferenceData();
}

// ── Reference data sync ───────────────────────────────────────────────────────

void PlanSyncManager::syncReferenceData()
{
#if defined(EC_GRPC_ENABLED)
    // Units — capture the unique_ptr in the lambda to manage lifetime
    auto unitsReply = m_grpcClient->GetUnits(calendar::Empty{});
    auto *rawUnits  = unitsReply.get();
    connect(rawUnits, &QGrpcCallReply::finished, this,
            [this, r = std::move(unitsReply)](const QGrpcStatus &status) {
        if (status.isOk()) {
            if (const auto resp = r->read<calendar::GetUnitsResponse>()) {
                QVariantList units;
                for (const auto &u : resp->units()) {
                    QVariantMap m;
                    m[QStringLiteral("id")]   = static_cast<int>(u.id_proto());
                    m[QStringLiteral("name")] = u.name();
                    units << m;
                }
                m_db->setUnits(units);
                qDebug() << "[PlanSyncManager] Loaded" << units.size() << "units from server";
            }
        } else {
            qWarning() << "[PlanSyncManager] GetUnits failed:" << status.message();
        }
    });

    // Routes
    auto routesReply = m_grpcClient->GetRoutes(calendar::Empty{});
    auto *rawRoutes  = routesReply.get();
    connect(rawRoutes, &QGrpcCallReply::finished, this,
            [this, r = std::move(routesReply)](const QGrpcStatus &status) {
        if (status.isOk()) {
            if (const auto resp = r->read<calendar::GetRoutesResponse>()) {
                QVariantList routes;
                for (const auto &rt : resp->routes()) {
                    QVariantMap m;
                    m[QStringLiteral("id")]   = static_cast<int>(rt.id_proto());
                    m[QStringLiteral("name")] = rt.name();
                    routes << m;
                }
                m_db->setRoutes(routes);
                qDebug() << "[PlanSyncManager] Loaded" << routes.size() << "routes from server";
            }
        } else {
            qWarning() << "[PlanSyncManager] GetRoutes failed:" << status.message();
        }
    });

#elif defined(Q_OS_WASM)
    // Units
    QNetworkRequest unitsReq(QUrl(m_serverUrl.toString() + QStringLiteral("/api/units")));
    auto *unitsReply = m_nam->get(unitsReq);
    connect(unitsReply, &QNetworkReply::finished, this, [unitsReply, this]() {
        if (unitsReply->error() == QNetworkReply::NoError) {
            const QJsonArray arr = QJsonDocument::fromJson(unitsReply->readAll())
                                       .object()[QStringLiteral("units")].toArray();
            QVariantList units;
            for (const QJsonValue &v : arr) {
                QVariantMap m;
                m[QStringLiteral("id")]   = v[QStringLiteral("id")].toInt();
                m[QStringLiteral("name")] = v[QStringLiteral("name")].toString();
                units << m;
            }
            m_db->setUnits(units);
            qDebug() << "[PlanSyncManager] Loaded" << units.size() << "units from server";
        } else {
            qWarning() << "[PlanSyncManager] GET /api/units failed:" << unitsReply->errorString();
        }
        unitsReply->deleteLater();
    });

    // Routes
    QNetworkRequest routesReq(QUrl(m_serverUrl.toString() + QStringLiteral("/api/routes")));
    auto *routesReply = m_nam->get(routesReq);
    connect(routesReply, &QNetworkReply::finished, this, [routesReply, this]() {
        if (routesReply->error() == QNetworkReply::NoError) {
            const QJsonArray arr = QJsonDocument::fromJson(routesReply->readAll())
                                       .object()[QStringLiteral("routes")].toArray();
            QVariantList routes;
            for (const QJsonValue &v : arr) {
                QVariantMap m;
                m[QStringLiteral("id")]   = v[QStringLiteral("id")].toInt();
                m[QStringLiteral("name")] = v[QStringLiteral("name")].toString();
                routes << m;
            }
            m_db->setRoutes(routes);
            qDebug() << "[PlanSyncManager] Loaded" << routes.size() << "routes from server";
        } else {
            qWarning() << "[PlanSyncManager] GET /api/routes failed:" << routesReply->errorString();
        }
        routesReply->deleteLater();
    });

#else
    // No transport — sync disabled.
#endif
}

// ── Plan push helpers ─────────────────────────────────────────────────────────

// Fills a PlanData protobuf message from a local Plan struct.
#if defined(EC_GRPC_ENABLED)
static calendar::PlanData planToProto(const Plan &plan)
{
    calendar::PlanData data;
    data.setName(plan.name);
    data.setStartDate(plan.startDate.date().toString(Qt::ISODate));
    data.setStartTimeSecs(plan.startDate.time().msecsSinceStartOfDay() / 1000);
    data.setEndDate(plan.endDate.date().toString(Qt::ISODate));
    data.setEndTimeSecs(plan.endDate.time().msecsSinceStartOfDay() / 1000);
    data.setUnitId(plan.unitId);
    QtProtobuf::int32List rids;
    for (int rid : plan.routeIds) rids << rid;
    data.setRouteIds(rids);
    return data;
}
#endif

void PlanSyncManager::pushAddedPlan(int id)
{
#if defined(EC_GRPC_ENABLED)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    calendar::AddPlanRequest req;
    req.setData(planToProto(plan));

    auto reply  = m_grpcClient->AddPlan(req);
    auto *rawPtr = reply.get();
    connect(rawPtr, &QGrpcCallReply::finished, this,
            [id, r = std::move(reply)](const QGrpcStatus &status) {
        if (!status.isOk())
            qWarning() << "[PlanSyncManager] AddPlan" << id << "failed:" << status.message();
    });

#elif defined(Q_OS_WASM)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    QJsonObject body;
    body[QStringLiteral("name")]          = plan.name;
    body[QStringLiteral("startDate")]     = plan.startDate.date().toString(Qt::ISODate);
    body[QStringLiteral("startTimeSecs")] = plan.startDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("endDate")]       = plan.endDate.date().toString(Qt::ISODate);
    body[QStringLiteral("endTimeSecs")]   = plan.endDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("unitId")]        = plan.unitId;
    QJsonArray rids;
    for (int rid : plan.routeIds) rids << rid;
    body[QStringLiteral("routeIds")] = rids;

    QNetworkRequest req(QUrl(m_serverUrl.toString() + QStringLiteral("/api/plans")));
    req.setHeader(QNetworkRequest::ContentTypeHeader, QStringLiteral("application/json"));
    auto *reply = m_nam->post(req, QJsonDocument(body).toJson(QJsonDocument::Compact));
    connect(reply, &QNetworkReply::finished, this, [reply, id]() {
        if (reply->error() != QNetworkReply::NoError)
            qWarning() << "[PlanSyncManager] POST /api/plans (id" << id << "):" << reply->errorString();
        reply->deleteLater();
    });
#else
    Q_UNUSED(id)
#endif
}

void PlanSyncManager::pushUpdatedPlan(int id)
{
#if defined(EC_GRPC_ENABLED)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    calendar::UpdatePlanRequest req;
    req.setId_proto(id);
    req.setData(planToProto(plan));

    auto reply   = m_grpcClient->UpdatePlan(req);
    auto *rawPtr = reply.get();
    connect(rawPtr, &QGrpcCallReply::finished, this,
            [id, r = std::move(reply)](const QGrpcStatus &status) {
        if (!status.isOk())
            qWarning() << "[PlanSyncManager] UpdatePlan" << id << "failed:" << status.message();
    });

#elif defined(Q_OS_WASM)
    const Plan plan = m_db->planById(id);
    if (plan.id < 0) return;

    QJsonObject body;
    body[QStringLiteral("name")]          = plan.name;
    body[QStringLiteral("startDate")]     = plan.startDate.date().toString(Qt::ISODate);
    body[QStringLiteral("startTimeSecs")] = plan.startDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("endDate")]       = plan.endDate.date().toString(Qt::ISODate);
    body[QStringLiteral("endTimeSecs")]   = plan.endDate.time().msecsSinceStartOfDay() / 1000;
    body[QStringLiteral("unitId")]        = plan.unitId;
    QJsonArray rids;
    for (int rid : plan.routeIds) rids << rid;
    body[QStringLiteral("routeIds")] = rids;

    QNetworkRequest req(QUrl(m_serverUrl.toString()
                             + QStringLiteral("/api/plans/") + QString::number(id)));
    req.setHeader(QNetworkRequest::ContentTypeHeader, QStringLiteral("application/json"));
    auto *reply = m_nam->put(req, QJsonDocument(body).toJson(QJsonDocument::Compact));
    connect(reply, &QNetworkReply::finished, this, [reply, id]() {
        if (reply->error() != QNetworkReply::NoError)
            qWarning() << "[PlanSyncManager] PUT /api/plans/" << id << ":" << reply->errorString();
        reply->deleteLater();
    });
#else
    Q_UNUSED(id)
#endif
}

void PlanSyncManager::pushDeletedPlan(int id)
{
#if defined(EC_GRPC_ENABLED)
    calendar::DeletePlanRequest req;
    req.setId_proto(id);

    auto reply   = m_grpcClient->DeletePlan(req);
    auto *rawPtr = reply.get();
    connect(rawPtr, &QGrpcCallReply::finished, this,
            [id, r = std::move(reply)](const QGrpcStatus &status) {
        if (!status.isOk())
            qWarning() << "[PlanSyncManager] DeletePlan" << id << "failed:" << status.message();
    });

#elif defined(Q_OS_WASM)
    QNetworkRequest req(QUrl(m_serverUrl.toString()
                             + QStringLiteral("/api/plans/") + QString::number(id)));
    auto *reply = m_nam->deleteResource(req);
    connect(reply, &QNetworkReply::finished, this, [reply, id]() {
        if (reply->error() != QNetworkReply::NoError)
            qWarning() << "[PlanSyncManager] DELETE /api/plans/" << id << ":" << reply->errorString();
        reply->deleteLater();
    });
#else
    Q_UNUSED(id)
#endif
}
